package com.petadoption.config;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

@Slf4j
@Component
@Order(0)
public class SchemaMigration implements CommandLineRunner {

    private final DataSource dataSource;

    public SchemaMigration(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public void run(String... args) {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            // ==================== 原有表 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_category (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(50) NOT NULL, description VARCHAR(200), " +
                "sort_order INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_user (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "username VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, " +
                "nickname VARCHAR(50), email VARCHAR(100), phone VARCHAR(20), " +
                "avatar VARCHAR(500), role VARCHAR(20) NOT NULL DEFAULT 'USER', " +
                "status SMALLINT DEFAULT 1, " +
                "bio TEXT, cert_status VARCHAR(20) DEFAULT 'UNCERTIFIED', " +
                "cert_data TEXT, shelter_name VARCHAR(100), shelter_address VARCHAR(200), " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_pet (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(50) NOT NULL, category_id BIGINT, breed VARCHAR(50), " +
                "age VARCHAR(20), gender VARCHAR(10), pet_size VARCHAR(20), " +
                "color VARCHAR(30), health_status VARCHAR(100), vaccination VARCHAR(100), " +
                "sterilization SMALLINT DEFAULT 0, description TEXT, " +
                "cover_image VARCHAR(500), status VARCHAR(20) DEFAULT 'AVAILABLE', " +
                "view_count INT DEFAULT 0, " +
                "personality VARCHAR(200), location VARCHAR(200), " +
                "is_adopted SMALLINT DEFAULT 0, adopted_at TIMESTAMP, adopted_by BIGINT, " +
                "weight VARCHAR(20), source VARCHAR(50), " +
                "created_by BIGINT, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_pet_image (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "pet_id BIGINT, url VARCHAR(500) NOT NULL, sort_order INT DEFAULT 0)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_adoption (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "pet_id BIGINT, user_id BIGINT, " +
                "real_name VARCHAR(50) NOT NULL, id_card VARCHAR(18) NOT NULL, " +
                "phone VARCHAR(20) NOT NULL, address VARCHAR(200) NOT NULL, " +
                "housing_type VARCHAR(50), has_experience SMALLINT DEFAULT 0, " +
                "family_agreed SMALLINT DEFAULT 0, occupation VARCHAR(50), " +
                "income_range VARCHAR(30), reason TEXT, " +
                "status VARCHAR(20) DEFAULT 'PENDING', " +
                "review_comment TEXT, reviewed_by BIGINT, reviewed_at TIMESTAMP, " +
                "owner_review_comment TEXT, owner_reviewed_by BIGINT, owner_reviewed_at TIMESTAMP, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_favorite (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT, pet_id BIGINT, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "CONSTRAINT uk_user_pet UNIQUE (user_id, pet_id))");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_comment (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "pet_id BIGINT, user_id BIGINT, " +
                "content TEXT NOT NULL, parent_id BIGINT DEFAULT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // ==================== 养宠测评 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_assessment (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT, answers TEXT, result_data TEXT, " +
                "pet_category VARCHAR(20), " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_assessment_question (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "question_text VARCHAR(500) NOT NULL, " +
                "question_type VARCHAR(20) DEFAULT 'SINGLE_CHOICE', " +
                "dimension VARCHAR(50), " +
                "options TEXT, pet_category VARCHAR(20) DEFAULT 'ALL', " +
                "weight DECIMAL(3,2) DEFAULT 1.0, sort_order INT DEFAULT 0)");

            // ==================== 流浪动物救助 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_rescue_post (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT, title VARCHAR(200) NOT NULL, " +
                "description TEXT, " +
                "latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, " +
                "address_desc VARCHAR(300), " +
                "animal_type VARCHAR(50), animal_desc VARCHAR(300), " +
                "emergency_level VARCHAR(20) DEFAULT 'NORMAL', " +
                "status VARCHAR(20) DEFAULT 'PENDING', " +
                "claimed_by BIGINT, claimed_at TIMESTAMP, " +
                "rescued_at TIMESTAMP, follow_up_text TEXT, " +
                "view_count INT DEFAULT 0, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_rescue_image (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "rescue_id BIGINT, url VARCHAR(500) NOT NULL, sort_order INT DEFAULT 0)");

            // ==================== 科普内容 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_article (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "title VARCHAR(200) NOT NULL, content TEXT, " +
                "summary VARCHAR(500), cover_image VARCHAR(500), " +
                "category VARCHAR(50) DEFAULT 'GENERAL', " +
                "status VARCHAR(20) DEFAULT 'PUBLISHED', " +
                "author_id BIGINT, view_count INT DEFAULT 0, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_article_tag (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(50) UNIQUE NOT NULL)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_article_tag_rel (" +
                "article_id BIGINT NOT NULL, tag_id BIGINT NOT NULL, " +
                "PRIMARY KEY (article_id, tag_id))");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_article_comment (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "article_id BIGINT NOT NULL, user_id BIGINT NOT NULL, " +
                "content TEXT NOT NULL, parent_id BIGINT DEFAULT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // ==================== 社区互动 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_community_post (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT, title VARCHAR(200) NOT NULL, " +
                "content TEXT, type VARCHAR(30) DEFAULT 'SHARING', " +
                "status VARCHAR(20) DEFAULT 'PUBLISHED', " +
                "view_count INT DEFAULT 0, like_count INT DEFAULT 0, " +
                "comment_count INT DEFAULT 0, is_reviewed SMALLINT DEFAULT 0, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_community_image (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "post_id BIGINT, url VARCHAR(500) NOT NULL, sort_order INT DEFAULT 0)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_community_like (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "post_id BIGINT, user_id BIGINT, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "CONSTRAINT uk_post_user_comm UNIQUE (post_id, user_id))");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_community_comment (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "post_id BIGINT, user_id BIGINT, " +
                "content TEXT NOT NULL, parent_id BIGINT DEFAULT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // ==================== 健康档案 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_health_record (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "pet_id BIGINT, user_id BIGINT, " +
                "record_type VARCHAR(30) DEFAULT 'DIARY', " +
                "title VARCHAR(200) NOT NULL, description TEXT, " +
                "record_date DATE, next_date DATE, " +
                "reminder_enabled SMALLINT DEFAULT 0, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_health_image (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "record_id BIGINT, url VARCHAR(500) NOT NULL, sort_order INT DEFAULT 0)");

            // ==================== 信任体系 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_review (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "reviewer_id BIGINT, target_id BIGINT, " +
                "adoption_id BIGINT, role_type VARCHAR(20), " +
                "rating INT DEFAULT 5, content TEXT, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            stmt.execute("CREATE TABLE IF NOT EXISTS t_blacklist (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "reporter_id BIGINT, target_id BIGINT, " +
                "reason TEXT, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // ==================== 公益板块 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_volunteer (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT UNIQUE, skills VARCHAR(300), " +
                "available_time VARCHAR(200), region VARCHAR(100), " +
                "status VARCHAR(20) DEFAULT 'ACTIVE', " +
                "welfare_activities TEXT, approved_at TIMESTAMP, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // 为已有数据库添加新字段
            stmt.execute("ALTER TABLE t_volunteer ADD COLUMN IF NOT EXISTS welfare_activities TEXT");
            stmt.execute("ALTER TABLE t_volunteer ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP");

            // ==================== 举报系统 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_system_report (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "reporter_id BIGINT, target_type VARCHAR(30), " +
                "target_id BIGINT, reason VARCHAR(300), " +
                "status VARCHAR(20) DEFAULT 'PENDING', " +
                "handler_note TEXT, handled_by BIGINT, handled_at TIMESTAMP, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // ==================== 通知系统 ====================
            stmt.execute("CREATE TABLE IF NOT EXISTS t_notification (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT, title VARCHAR(200) NOT NULL, " +
                "content VARCHAR(500), type VARCHAR(30), " +
                "related_id BIGINT, is_read SMALLINT DEFAULT 0, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            log.info("数据库表结构初始化完成");

        } catch (Exception e) {
            log.error("数据库初始化失败: {}", e.getMessage(), e);
            throw new RuntimeException("数据库初始化失败", e);
        }
    }
}
